// AUTO-GENERATED by data-raw/update_nominal_indices.R -- do not edit by hand.
//
// Headline nominal indices, expressed relative to calendar 2021 = 1.0, which
// is the year the fplida spine draws each person's baseline income at.
//
// Sources, per column:
//   wage      ATO Taxation statistics, Individuals Table 1A: total salary or
//             wages / individuals reporting salary or wages.
//   price     ABS Consumer Price Index, All groups, Australia, original.
//   business  ATO Taxation statistics, Company Table 1A: total income /
//             number of companies.
//   transfer  ABS Average Weekly Earnings, full-time adult total earnings,
//             males (MTAWE), the Age Pension benchmark.
//   health    Medicare Benefits Schedule annual indexation factor,
//             data-raw/nominal-sources/administered-indexation.csv.
//
// `projected` marks a year outside the published data, filled by compounding
// the trailing ten-year average growth of the series.

#[derive(Debug, Clone, Copy)]
pub struct NominalRow {
    pub year: i32,
    pub wage: f64,
    pub price: f64,
    pub business: f64,
    pub transfer: f64,
    pub health: f64,
    pub projected: bool,
}

/// First year in both tables (a financial year is named by the July it starts in).
pub const FIRST_YEAR: i32 = 1994;
/// Last year in both tables.
pub const LAST_YEAR: i32 = 2029;
/// The calendar year every index is 1.0 in.
pub const ANCHOR_YEAR: i32 = 2021;

/// Financial-year basis: 2011 means the year ended 30 June 2012.
pub const FINANCIAL_YEAR: [NominalRow; 36] = [
    NominalRow { year: 1994, wage: 0.36974059, price: 0.52776987, business: 0.54053592, transfer: 0.38225176, health: 0.64961282, projected: true },
    NominalRow { year: 1995, wage: 0.38507993, price: 0.55009364, business: 0.57539292, transfer: 0.39980268, health: 0.66260508, projected: true },
    NominalRow { year: 1996, wage: 0.40176918, price: 0.55731515, business: 0.58810435, transfer: 0.41153791, health: 0.67585718, projected: true },
    NominalRow { year: 1997, wage: 0.42060534, price: 0.55722526, business: 0.60760429, transfer: 0.42703776, health: 0.68937432, projected: true },
    NominalRow { year: 1998, wage: 0.43785188, price: 0.56450670, business: 0.64744648, transfer: 0.44116158, health: 0.70316181, projected: true },
    NominalRow { year: 1999, wage: 0.45609814, price: 0.57790097, business: 0.65229928, transfer: 0.45372762, health: 0.71722505, projected: true },
    NominalRow { year: 2000, wage: 0.47825700, price: 0.61242041, business: 0.66617558, transfer: 0.47060351, health: 0.73156955, projected: true },
    NominalRow { year: 2001, wage: 0.49294889, price: 0.62997977, business: 0.68010672, transfer: 0.49511248, health: 0.74620094, projected: true },
    NominalRow { year: 2002, wage: 0.51115899, price: 0.64939696, business: 0.67898394, transfer: 0.52419093, health: 0.76112496, projected: true },
    NominalRow { year: 2003, wage: 0.53340968, price: 0.66470897, business: 0.66975343, transfer: 0.54740176, health: 0.77634746, projected: true },
    NominalRow { year: 2004, wage: 0.55747522, price: 0.68077010, business: 0.69985310, transfer: 0.57562343, health: 0.79187440, projected: true },
    NominalRow { year: 2005, wage: 0.58268571, price: 0.70270432, business: 0.74232281, transfer: 0.59540716, health: 0.80771189, projected: true },
    NominalRow { year: 2006, wage: 0.61056337, price: 0.72320024, business: 0.81400109, transfer: 0.61955266, health: 0.82386613, projected: true },
    NominalRow { year: 2007, wage: 0.63897590, price: 0.74780133, business: 0.87787219, transfer: 0.64813781, health: 0.84182641, projected: false },
    NominalRow { year: 2008, wage: 0.67566780, price: 0.77102405, business: 0.91507240, transfer: 0.68552439, health: 0.86110424, projected: false },
    NominalRow { year: 2009, wage: 0.70215689, price: 0.78900292, business: 0.87079418, transfer: 0.72319655, health: 0.88039297, projected: false },
    NominalRow { year: 2010, wage: 0.74146197, price: 0.81351412, business: 0.92368097, transfer: 0.75520881, health: 0.89579985, projected: false },
    NominalRow { year: 2011, wage: 0.77772184, price: 0.83242190, business: 0.94233398, transfer: 0.78935002, health: 0.91380543, projected: false },
    NominalRow { year: 2012, wage: 0.81611632, price: 0.85114990, business: 0.95659667, transfer: 0.82650293, health: 0.93180739, projected: false },
    NominalRow { year: 2013, wage: 0.83147352, price: 0.87434265, business: 0.92523145, transfer: 0.84890891, health: 0.93180739, projected: false },
    NominalRow { year: 2014, wage: 0.84436091, price: 0.88920518, business: 0.92041354, transfer: 0.87131489, health: 0.95109581, projected: false },
    NominalRow { year: 2015, wage: 0.86182954, price: 0.90140085, business: 0.91181201, transfer: 0.87835084, health: 0.95109581, projected: false },
    NominalRow { year: 2016, wage: 0.86740846, price: 0.91683272, business: 0.90816088, transfer: 0.89460361, health: 0.95109581, projected: false },
    NominalRow { year: 2017, wage: 0.89838284, price: 0.93466177, business: 0.94186327, transfer: 0.91475082, health: 0.95109581, projected: false },
    NominalRow { year: 2018, wage: 0.92333361, price: 0.94988389, business: 0.96129452, transfer: 0.93370374, health: 0.96536224, projected: false },
    NominalRow { year: 2019, wage: 0.94207632, price: 0.96273878, business: 0.95568450, transfer: 0.96890943, health: 0.98080804, projected: false },
    NominalRow { year: 2020, wage: 0.97663625, price: 0.97808076, business: 0.97208205, transfer: 0.98801812, health: 0.99552016, projected: false },
    NominalRow { year: 2021, wage: 1.02336375, price: 1.02191924, business: 1.02791795, transfer: 1.01198188, health: 1.00447984, projected: false },
    NominalRow { year: 2022, wage: 1.07954489, price: 1.09371489, business: 1.13369781, transfer: 1.04853764, health: 1.02055152, projected: false },
    NominalRow { year: 2023, wage: 1.12933588, price: 1.13953105, business: 1.18470675, transfer: 1.08846858, health: 1.06239413, projected: false },
    NominalRow { year: 2024, wage: 1.16444933, price: 1.16730841, business: 1.21435848, transfer: 1.13733075, health: 1.09957792, projected: true },
    NominalRow { year: 2025, wage: 1.20065454, price: 1.21075736, business: 1.24475236, transfer: 1.16804062, health: 1.12596780, projected: true },
    NominalRow { year: 2026, wage: 1.23798544, price: 1.24701315, business: 1.27590696, transfer: 1.19957971, health: 1.14513355, projected: true },
    NominalRow { year: 2027, wage: 1.27647704, price: 1.28435461, business: 1.30784132, transfer: 1.23197041, health: 1.16462554, projected: true },
    NominalRow { year: 2028, wage: 1.31616542, price: 1.32281425, business: 1.34057495, transfer: 1.26523571, health: 1.18444931, projected: true },
    NominalRow { year: 2029, wage: 1.35708780, price: 1.36242555, business: 1.37412787, transfer: 1.29939923, health: 1.20461052, projected: true },
];

/// Calendar-year basis.
pub const CALENDAR_YEAR: [NominalRow; 36] = [
    NominalRow { year: 1994, wage: 0.36974059, price: 0.52776987, business: 0.54053592, transfer: 0.38225176, health: 0.64961282, projected: true },
    NominalRow { year: 1995, wage: 0.37741026, price: 0.53893176, business: 0.55796442, transfer: 0.39102722, health: 0.65610895, projected: true },
    NominalRow { year: 1996, wage: 0.39342455, price: 0.55370440, business: 0.58174863, transfer: 0.40567030, health: 0.66923113, projected: true },
    NominalRow { year: 1997, wage: 0.41118726, price: 0.55727021, business: 0.59785432, transfer: 0.41928784, health: 0.68261575, projected: true },
    NominalRow { year: 1998, wage: 0.42922861, price: 0.56086598, business: 0.62752539, transfer: 0.43409967, health: 0.69626807, projected: true },
    NominalRow { year: 1999, wage: 0.44697501, price: 0.57120384, business: 0.64987288, transfer: 0.44744460, health: 0.71019343, projected: true },
    NominalRow { year: 2000, wage: 0.46717757, price: 0.59516069, business: 0.65923743, transfer: 0.46216557, health: 0.72439730, projected: true },
    NominalRow { year: 2001, wage: 0.48560295, price: 0.62120009, business: 0.67314115, transfer: 0.48285800, health: 0.73888524, projected: true },
    NominalRow { year: 2002, wage: 0.50205394, price: 0.63968837, business: 0.67954533, transfer: 0.50965171, health: 0.75366295, projected: true },
    NominalRow { year: 2003, wage: 0.52228434, price: 0.65705296, business: 0.67436869, transfer: 0.53579635, health: 0.76873621, projected: true },
    NominalRow { year: 2004, wage: 0.54544245, price: 0.67273953, business: 0.68480327, transfer: 0.56151260, health: 0.78411093, projected: true },
    NominalRow { year: 2005, wage: 0.57008046, price: 0.69173721, business: 0.72108795, transfer: 0.58551530, health: 0.79979315, projected: true },
    NominalRow { year: 2006, wage: 0.59662454, price: 0.71295228, business: 0.77816195, transfer: 0.60747991, health: 0.81578901, projected: true },
    NominalRow { year: 2007, wage: 0.62476963, price: 0.73550079, business: 0.84593664, transfer: 0.63384524, health: 0.83284627, projected: true },
    NominalRow { year: 2008, wage: 0.65732185, price: 0.75941269, business: 0.89647230, transfer: 0.66683110, health: 0.85146532, projected: false },
    NominalRow { year: 2009, wage: 0.68891234, price: 0.78001348, business: 0.89293329, transfer: 0.70436047, health: 0.87074860, projected: false },
    NominalRow { year: 2010, wage: 0.72180943, price: 0.80125852, business: 0.89723758, transfer: 0.73920268, health: 0.88809641, projected: false },
    NominalRow { year: 2011, wage: 0.75959191, price: 0.82296801, business: 0.93300748, transfer: 0.77227941, health: 0.90480264, projected: false },
    NominalRow { year: 2012, wage: 0.79691908, price: 0.84178590, business: 0.94946533, transfer: 0.80792647, health: 0.92280641, projected: false },
    NominalRow { year: 2013, wage: 0.82379492, price: 0.86274627, business: 0.94091406, transfer: 0.83770592, health: 0.93180739, projected: false },
    NominalRow { year: 2014, wage: 0.83791722, price: 0.88177392, business: 0.92282250, transfer: 0.86011190, health: 0.94145160, projected: false },
    NominalRow { year: 2015, wage: 0.85309523, price: 0.89530302, business: 0.91611278, transfer: 0.87483286, health: 0.95109581, projected: false },
    NominalRow { year: 2016, wage: 0.86461900, price: 0.90911679, business: 0.90998645, transfer: 0.88647722, health: 0.95109581, projected: false },
    NominalRow { year: 2017, wage: 0.88289565, price: 0.92574725, business: 0.92501208, transfer: 0.90467722, health: 0.95109581, projected: false },
    NominalRow { year: 2018, wage: 0.91085822, price: 0.94227283, business: 0.95157889, transfer: 0.92422728, health: 0.95822902, projected: false },
    NominalRow { year: 2019, wage: 0.93270496, price: 0.95631133, business: 0.95848951, transfer: 0.95130658, health: 0.97308514, projected: false },
    NominalRow { year: 2020, wage: 0.95935628, price: 0.97040977, business: 0.96388327, transfer: 0.97846378, health: 0.98816410, projected: false },
    NominalRow { year: 2021, wage: 1.00000000, price: 1.00000000, business: 1.00000000, transfer: 1.00000000, health: 1.00000000, projected: false },
    NominalRow { year: 2022, wage: 1.05145432, price: 1.05781706, business: 1.08080788, transfer: 1.03025976, health: 1.01251568, projected: false },
    NominalRow { year: 2023, wage: 1.10444038, price: 1.11662297, business: 1.15920228, transfer: 1.06850311, health: 1.04147282, projected: false },
    NominalRow { year: 2024, wage: 1.14689261, price: 1.15341973, business: 1.19953262, transfer: 1.11289967, health: 1.08098603, projected: true },
    NominalRow { year: 2025, wage: 1.18255194, price: 1.18903289, business: 1.22955542, transfer: 1.15268569, health: 1.11277286, projected: true },
    NominalRow { year: 2026, wage: 1.21931999, price: 1.22888525, business: 1.26032966, transfer: 1.18381017, health: 1.13555067, projected: true },
    NominalRow { year: 2027, wage: 1.25723124, price: 1.26568388, business: 1.29187414, transfer: 1.21577506, health: 1.15487955, projected: true },
    NominalRow { year: 2028, wage: 1.29632123, price: 1.30358443, business: 1.32420814, transfer: 1.24860306, health: 1.17453743, projected: true },
    NominalRow { year: 2029, wage: 1.33662661, price: 1.34261990, business: 1.35735141, transfer: 1.28231747, health: 1.19452991, projected: true },
];

