blank_issues_enabled: false
contact_links:
  - name: ABS microdata access information
    url: https://www.abs.gov.au/statistics/microdata-tablebuilder/available-microdata-tablebuilder
    about: Use this service for questions about access to official ABS microdata.
