# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_fplida_wrappers", use_symbols = TRUE, package_name = "fplida")

#' @useDynLib fplida, .registration = TRUE
NULL

#' Return the package version string.
#' @export
fplida_version <- function() .Call(wrap__fplida_version)

#' @rdname rust-internals
#' @export
set_business_pool__ <- function(bns) .Call(wrap__set_business_pool__, bns)

#' @rdname rust-internals
#' @export
business_pool_size__ <- function() .Call(wrap__business_pool_size__)

#' @rdname rust-internals
#' @export
blade_stable_name_seed__ <- function(value) .Call(wrap__blade_stable_name_seed__, value)

#' @rdname rust-internals
#' @export
make_blade_business_spine__ <- function(
    spine_state, spine_industry, spine_sector, baseline_employed, baseline_income,
    spine_id, aeuid_ato, anzsco_code, anzsco_title, seed, n_businesses
) .Call(wrap__make_blade_business_spine__,
    spine_state, spine_industry, spine_sector, baseline_employed, baseline_income,
    spine_id, aeuid_ato, anzsco_code, anzsco_title, seed, n_businesses)

#' @rdname rust-internals
#' @export
make_blade_person_link__ <- function(
    spine_state, baseline_employed, baseline_income, spine_id, aeuid_ato,
    aeuid_abs, aeuid_dhda, anzsco_code, anzsco_title, birth_year, sex,
    bs_state, bs_bn, bs_id, bs_bg_id, bs_health_flag, seed
) .Call(wrap__make_blade_person_link__,
    spine_state, baseline_employed, baseline_income, spine_id, aeuid_ato,
    aeuid_abs, aeuid_dhda, anzsco_code, anzsco_title, birth_year, sex,
    bs_state, bs_bn, bs_id, bs_bg_id, bs_health_flag, seed)

#' @rdname rust-internals
#' @export
generate_census_2021_person__ <- function(n, seed) .Call(wrap__generate_census_2021_person, n, seed)

#' @rdname rust-internals
#' @export
project_census_person__ <- function(
    aeuid_abs, birth_year, sex, state, indigenous,
    country_of_birth_sacc, year_of_arrival, citizenship,
    education, baseline_employed, baseline_hours,
    anzsco_code, anzsco_major, industry, valid_anzsco_codes,
    disability_onset_year, disability_severity, task_physical, sa2, seed
) .Call(wrap__project_census_person__,
    aeuid_abs, birth_year, sex, state, indigenous,
    country_of_birth_sacc, year_of_arrival, citizenship,
    education, baseline_employed, baseline_hours,
    anzsco_code, anzsco_major, industry, valid_anzsco_codes,
    disability_onset_year, disability_severity, task_physical, sa2, seed)

#' @rdname rust-internals
#' @export
generate_census_2021_dwelling__ <- function(n, seed) .Call(wrap__generate_census_2021_dwelling, n, seed)

#' @rdname rust-internals
#' @export
generate_census_2021_family__ <- function(n, seed) .Call(wrap__generate_census_2021_family, n, seed)

#' @rdname rust-internals
#' @export
generate_spine__ <- function(n, seed) .Call(wrap__generate_spine, n, seed)

#' @rdname rust-internals
#' @export
generate_mbs_year__ <- function(
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    item_num, item_category, item_group, item_sub_heading,
    item_benefit_type, item_schedule_fee, item_benefit_75,
    item_benefit_85, item_benefit_100, item_weight,
    provider_pool, ref_pool, prac_pool,
    year, seed
) .Call(wrap__generate_mbs_year__,
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    item_num, item_category, item_group, item_sub_heading,
    item_benefit_type, item_schedule_fee, item_benefit_75,
    item_benefit_85, item_benefit_100, item_weight,
    provider_pool, ref_pool, prac_pool,
    year, seed)

#' @rdname rust-internals
#' @export
generate_mbs_year_parquet__ <- function(
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    item_num, item_category, item_group, item_sub_heading,
    item_benefit_type, item_schedule_fee, item_benefit_75,
    item_benefit_85, item_benefit_100, item_weight,
    provider_pool, ref_pool, prac_pool,
    year, seed, out_path
) .Call(wrap__generate_mbs_year_parquet__,
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    item_num, item_category, item_group, item_sub_heading,
    item_benefit_type, item_schedule_fee, item_benefit_75,
    item_benefit_85, item_benefit_100, item_weight,
    provider_pool, ref_pool, prac_pool,
    year, seed, out_path)

#' @rdname rust-internals
#' @export
select_mbs_participants__ <- function(birth_year, min_year, max_year, seed) {
  .Call(wrap__select_mbs_participants__, birth_year, min_year, max_year, seed)
}

#' @rdname rust-internals
#' @export
generate_pbs_year__ <- function(
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    pbs_code, atc_code, atc_level1, benefit_type, claimed_price,
    pack_size, number_of_repeats, item_weight,
    prescriber_pool, pharmacy_pool,
    year, seed
) .Call(wrap__generate_pbs_year__,
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    pbs_code, atc_code, atc_level1, benefit_type, claimed_price,
    pack_size, number_of_repeats, item_weight,
    prescriber_pool, pharmacy_pool,
    year, seed)

#' @rdname rust-internals
#' @export
generate_pbs_year_parquet__ <- function(
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    pbs_code, atc_code, atc_level1, benefit_type, claimed_price,
    pack_size, number_of_repeats, item_weight,
    prescriber_pool, pharmacy_pool,
    year, seed, out_path
) .Call(wrap__generate_pbs_year_parquet__,
    aeuid, birth_year, month_of_birth, sex, state, first_year, last_year,
    pbs_code, atc_code, atc_level1, benefit_type, claimed_price,
    pack_size, number_of_repeats, item_weight,
    prescriber_pool, pharmacy_pool,
    year, seed, out_path)

#' @rdname rust-internals
#' @export
select_pbs_participants__ <- function(birth_year, min_year, max_year, seed) {
  .Call(wrap__select_pbs_participants__, birth_year, min_year, max_year, seed)
}

#' @rdname rust-internals
#' @export
select_he_participants__ <- function(
    birth_year, sex, state, education, archetype,
    country_of_birth, indigenous, aeuid,
    seed, min_year, max_year
) .Call(wrap__select_he_participants__,
    birth_year, sex, state, education, archetype,
    country_of_birth, indigenous, aeuid,
    seed, min_year, max_year)

#' @rdname rust-internals
#' @export
project_he_load__ <- function(
    spell_aeuid, spell_commence_year, spell_actual_duration,
    spell_completed, spell_is_ft, spell_qual_idx,
    spell_foe, spell_inst_code, spell_inst_state,
    spell_country_of_birth, spell_attend_mode, spell_course_code,
    min_year, max_year, seed
) .Call(wrap__project_he_load__,
    spell_aeuid, spell_commence_year, spell_actual_duration,
    spell_completed, spell_is_ft, spell_qual_idx,
    spell_foe, spell_inst_code, spell_inst_state,
    spell_country_of_birth, spell_attend_mode, spell_course_code,
    min_year, max_year, seed)

#' @rdname rust-internals
#' @export
project_he_enrol__ <- function(
    spell_aeuid, spell_commence_year, spell_actual_duration,
    spell_is_ft, spell_course_code, spell_inst_code,
    spell_attend_mode, spell_sex, spell_country_of_birth,
    spell_indigenous, spell_disability_type, spell_disability_support,
    spell_education, spell_birth_year,
    min_year, max_year
) .Call(wrap__project_he_enrol__,
    spell_aeuid, spell_commence_year, spell_actual_duration,
    spell_is_ft, spell_course_code, spell_inst_code,
    spell_attend_mode, spell_sex, spell_country_of_birth,
    spell_indigenous, spell_disability_type, spell_disability_support,
    spell_education, spell_birth_year,
    min_year, max_year)

#' @rdname rust-internals
#' @export
project_he_course__ <- function(
    spell_aeuid, spell_commence_year, spell_course_code,
    spell_qual_idx, spell_foe, spell_inst_code,
    spell_is_ft, spell_actual_duration
) .Call(wrap__project_he_course__,
    spell_aeuid, spell_commence_year, spell_course_code,
    spell_qual_idx, spell_foe, spell_inst_code,
    spell_is_ft, spell_actual_duration)

#' @rdname rust-internals
#' @export
project_he_completions__ <- function(
    spell_aeuid, spell_completed, spell_completion_year,
    spell_course_code, spell_qual_idx, spell_foe,
    spell_inst_code, max_year
) .Call(wrap__project_he_completions__,
    spell_aeuid, spell_completed, spell_completion_year,
    spell_course_code, spell_qual_idx, spell_foe,
    spell_inst_code, max_year)

#' @rdname rust-internals
#' @export
project_he_help__ <- function(
    load_aeuid, load_year, load_institution,
    load_help_debt, load_student_status, load_loan_fee
) .Call(wrap__project_he_help__,
    load_aeuid, load_year, load_institution,
    load_help_debt, load_student_status, load_loan_fee)

#' @rdname rust-internals
#' @export
project_core_demographics__ <- function(
    spine_id, birth_year, sex, country_of_birth_sacc, seed
) .Call(wrap__project_core_demographics__,
    spine_id, birth_year, sex, country_of_birth_sacc, seed)

#' @rdname rust-internals
#' @export
project_core_locations__ <- function(
    spine_id, state, sa2, lookup_state, lookup_mb_code,
    lookup_sa1_code, lookup_sa2_code, lookup_sa4_code, seed
) .Call(wrap__project_core_locations__,
    spine_id, state, sa2, lookup_state, lookup_mb_code,
    lookup_sa1_code, lookup_sa2_code, lookup_sa4_code, seed)

#' @rdname rust-internals
#' @export
project_core_relationships__ <- function(
    spine_id, birth_year, household_id, seed
) .Call(wrap__project_core_relationships__,
    spine_id, birth_year, household_id, seed)

#' @rdname rust-internals
#' @export
project_core_residence_to_parquet__ <- function(
    spine_id, birth_year, month_of_birth, country_of_birth, year_of_arrival,
    year_of_death, month_of_death, day_of_death, residence_seed,
    min_year, max_year, out_dir, product_name
) .Call(wrap__project_core_residence_to_parquet__,
    spine_id, birth_year, month_of_birth, country_of_birth, year_of_arrival,
    year_of_death, month_of_death, day_of_death, residence_seed,
    min_year, max_year, out_dir, product_name)

#' @rdname rust-internals
#' @export
select_tva_participants__ <- function(
    birth_year, education, archetype, aeuid_ncver,
    anzsco_code, sex, state, seed, min_year, max_year
) .Call(wrap__select_tva_participants__,
    birth_year, education, archetype, aeuid_ncver,
    anzsco_code, sex, state, seed, min_year, max_year)

#' @rdname rust-internals
#' @export
project_tva_activity__ <- function(
    spell_aeuid, spell_birth_year, spell_sex, spell_state,
    spell_education, spell_anzsco, spell_qual_idx, spell_foe,
    spell_commence_year, spell_duration_yrs, spell_is_ft,
    spell_completion_year, spell_rto_id, spell_prov_type,
    years, seed
) .Call(wrap__project_tva_activity__,
    spell_aeuid, spell_birth_year, spell_sex, spell_state,
    spell_education, spell_anzsco, spell_qual_idx, spell_foe,
    spell_commence_year, spell_duration_yrs, spell_is_ft,
    spell_completion_year, spell_rto_id, spell_prov_type,
    years, seed)

#' @rdname rust-internals
#' @export
project_tva_completions__ <- function(
    spell_aeuid, spell_birth_year, spell_sex, spell_state,
    spell_education, spell_anzsco, spell_qual_idx, spell_foe,
    spell_completion_year, spell_completed, spell_rto_id,
    spell_prov_type, seed, min_year, max_year
) .Call(wrap__project_tva_completions__,
    spell_aeuid, spell_birth_year, spell_sex, spell_state,
    spell_education, spell_anzsco, spell_qual_idx, spell_foe,
    spell_completion_year, spell_completed, spell_rto_id,
    spell_prov_type, seed, min_year, max_year)

#' @rdname rust-internals
#' @export
select_domino_participants__ <- function(
    birth_year, baseline_income, sex, education, aeuid_dss,
    disability_onset_year, disability_is_dc, disability_severity,
    seed, min_year, max_year
) .Call(wrap__select_domino_participants__,
    birth_year, baseline_income, sex, education, aeuid_dss,
    disability_onset_year, disability_is_dc, disability_severity,
    seed, min_year, max_year)

#' @rdname rust-internals
#' @export
generate_benefit_spells__ <- function(
    aeuid, primary_ben, first_year, last_year, death_day,
    seed, min_year, max_year
) .Call(wrap__generate_benefit_spells__,
    aeuid, primary_ben, first_year, last_year, death_day,
    seed, min_year, max_year)

#' @rdname rust-internals
#' @export
generate_medical_assessments__ <- function(
    det_ben_aeuid, det_ben_type_code, det_ben_period_start_date,
    seed
) .Call(wrap__generate_medical_assessments__,
    det_ben_aeuid, det_ben_type_code, det_ben_period_start_date,
    seed)

#' @rdname rust-internals
#' @export
generate_payment_history__ <- function(
    det_ben_aeuid, det_ben_type_code, det_ben_period_start_date,
    det_ben_period_end_date, seed
) .Call(wrap__generate_payment_history__,
    det_ben_aeuid, det_ben_type_code, det_ben_period_start_date,
    det_ben_period_end_date, seed)

#' @rdname rust-internals
#' @export
project_domino_demogs__ <- function(
    participant_aeuid, participant_spine_idx, spine_birth_year,
    spine_month_of_birth, spine_sex, spine_country_of_birth,
    spine_year_of_death, spine_month_of_death, seed
) .Call(wrap__project_domino_demogs__,
    participant_aeuid, participant_spine_idx, spine_birth_year,
    spine_month_of_birth, spine_sex, spine_country_of_birth,
    spine_year_of_death, spine_month_of_death, seed)

#' @rdname rust-internals
#' @export
project_domino_income__ <- function(
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_baseline_income, seed
) .Call(wrap__project_domino_income__,
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_baseline_income, seed)

#' @rdname rust-internals
#' @export
project_domino_locations__ <- function(
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_state, seed
) .Call(wrap__project_domino_locations__,
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_state, seed)

#' @rdname rust-internals
#' @export
project_domino_education__ <- function(
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_education, seed
) .Call(wrap__project_domino_education__,
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_education, seed)

#' @rdname rust-internals
#' @export
project_domino_housing__ <- function(
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_baseline_income, seed
) .Call(wrap__project_domino_housing__,
    participant_aeuid, participant_spine_idx, participant_first_year,
    participant_last_year, spine_baseline_income, seed)

#' @rdname rust-internals
#' @export
project_domino_indigenous__ <- function(
    participant_aeuid, participant_spine_idx, spine_indigenous
) .Call(wrap__project_domino_indigenous__,
    participant_aeuid, participant_spine_idx, spine_indigenous)

#' @rdname rust-internals
#' @export
project_domino_principal_carer__ <- function(
    det_ben_aeuid, det_ben_type_code, det_ben_period_start_date,
    det_ben_period_end_date, seed
) .Call(wrap__project_domino_principal_carer__,
    det_ben_aeuid, det_ben_type_code, det_ben_period_start_date,
    det_ben_period_end_date, seed)

#' @rdname rust-internals
#' @export
person_fy_wages__ <- function(
    id, aeuid_ato, birth_year, baseline_employed,
    baseline_income, baseline_hours, anzsco_major,
    industry, seed, years,
    disability_onset_year, disability_is_dc,
    disability_severity, disability_dose,
    anzsco_code, task_physical, archetype
) .Call(wrap__person_fy_wages__,
    id, aeuid_ato, birth_year, baseline_employed,
    baseline_income, baseline_hours, anzsco_major,
    industry, seed, years,
    disability_onset_year, disability_is_dc,
    disability_severity, disability_dose,
    anzsco_code, task_physical, archetype)

#' @rdname rust-internals
#' @export
generate_employment_panel__ <- function(
    id, aeuid_ato, birth_year, baseline_employed,
    baseline_income, baseline_hours, anzsco_major,
    industry, seed, years,
    disability_onset_year, disability_is_dc,
    disability_severity, disability_dose,
    target_year,
    anzsco_code, task_physical, archetype
) .Call(wrap__generate_employment_panel__,
    id, aeuid_ato, birth_year, baseline_employed,
    baseline_income, baseline_hours, anzsco_major,
    industry, seed, years,
    disability_onset_year, disability_is_dc,
    disability_severity, disability_dose,
    target_year,
    anzsco_code, task_physical, archetype)

#' @rdname rust-internals
#' @export
assign_disability__ <- function(
    birth_year, education, baseline_employed,
    task_cognitive, task_physical, task_vision,
    task_hearing, task_manual_dexterity, task_communication,
    seed, onset_min_year, onset_max_year, disability_rate
) .Call(wrap__assign_disability__,
    birth_year, education, baseline_employed,
    task_cognitive, task_physical, task_vision,
    task_hearing, task_manual_dexterity, task_communication,
    seed, onset_min_year, onset_max_year, disability_rate)

#' @rdname rust-internals
#' @export
project_combined_indigenous__ <- function(spine_id, indigenous) {
  .Call(wrap__project_combined_indigenous__, spine_id, indigenous)
}

#' @rdname rust-internals
#' @export
project_mcd__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, year_of_death, month_of_death, seed
) .Call(wrap__project_mcd__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, year_of_death, month_of_death, seed)

#' @rdname rust-internals
#' @export
project_ato_cr__ <- function(
    aeuid, birth_year, sex, state, country_of_birth, seed,
    reference_year
) .Call(wrap__project_ato_cr__,
    aeuid, birth_year, sex, state, country_of_birth, seed,
    reference_year)

#' @rdname rust-internals
#' @export
project_visa__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, indigenous, anzsco_code, baseline_income, seed
) .Call(wrap__project_visa__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, indigenous, anzsco_code, baseline_income, seed)

#' @rdname rust-internals
#' @export
project_mt_demogs__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, seed
) .Call(wrap__project_mt_demogs__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, seed)

#' @rdname rust-internals
#' @export
project_sdb__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, education, anzsco_code, seed
) .Call(wrap__project_sdb__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, education, anzsco_code, seed)

#' @rdname rust-internals
#' @export
project_travellers__ <- function(
    aeuid, birth_year, month_of_birth, country_of_birth, year_of_arrival,
    year_of_death, month_of_death, day_of_death, residence_seed,
    seed, min_year, max_year
) .Call(wrap__project_travellers__,
    aeuid, birth_year, month_of_birth, country_of_birth, year_of_arrival,
    year_of_death, month_of_death, day_of_death, residence_seed,
    seed, min_year, max_year)

.project_traveller_dil_values__ <- function(
    kind, year, period, birth_year, month_of_birth, country_of_birth,
    year_of_arrival, year_of_death, month_of_death, day_of_death,
    residence_seed
) .Call(wrap__project_traveller_dil_values__,
    kind, year, period, birth_year, month_of_birth, country_of_birth,
    year_of_arrival, year_of_death, month_of_death, day_of_death,
    residence_seed)

.project_traveller_reference_values__ <- function(
    reference_year, citizenship, country_of_birth_sacc, birth_year,
    year_of_arrival, year_of_death, residence_seed
) .Call(wrap__project_traveller_reference_values__,
    reference_year, citizenship, country_of_birth_sacc, birth_year,
    year_of_arrival, year_of_death, residence_seed)

#' @rdname rust-internals
#' @export
project_pit_ie__ <- function(
    aeuid, birth_year, baseline_employed, baseline_income,
    education, seed, fy_start, fy_end
) .Call(wrap__project_pit_ie__,
    aeuid, birth_year, baseline_employed, baseline_income,
    education, seed, fy_start, fy_end)

#' @rdname rust-internals
#' @export
project_busown__ <- function(
    aeuid, birth_year, baseline_employed, seed, fy_start, fy_end
) .Call(wrap__project_busown__,
    aeuid, birth_year, baseline_employed, seed, fy_start, fy_end)

#' @rdname rust-internals
#' @export
project_sae__ <- function(
    aeuid, birth_year, sex, state, baseline_employed,
    baseline_income, seed, fy_start, fy_end
) .Call(wrap__project_sae__,
    aeuid, birth_year, sex, state, baseline_employed,
    baseline_income, seed, fy_start, fy_end)

#' @rdname rust-internals
#' @export
project_cgt__ <- function(
    aeuid, birth_year, baseline_income, seed, fy_start, fy_end
) .Call(wrap__project_cgt__,
    aeuid, birth_year, baseline_income, seed, fy_start, fy_end)

#' @rdname rust-internals
#' @export
project_rps__ <- function(
    aeuid, birth_year, baseline_income, state, seed, fy_start, fy_end
) .Call(wrap__project_rps__,
    aeuid, birth_year, baseline_income, state, seed, fy_start, fy_end)

#' @rdname rust-internals
#' @export
project_deaths__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, seed, min_year, max_year
) .Call(wrap__project_deaths__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, seed, min_year, max_year)

#' @rdname rust-internals
#' @export
project_ndis_participants__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    disability_onset_year, disability_severity, person_type, seed
) .Call(wrap__project_ndis_participants__,
    aeuid, birth_year, sex, state, indigenous,
    disability_onset_year, disability_severity, person_type, seed)

#' @rdname rust-internals
#' @export
project_apprentice__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, anzsco_code, industry,
    year_of_death, month_of_death, day_of_death, seed
) .Call(wrap__project_apprentice__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, anzsco_code, industry,
    year_of_death, month_of_death, day_of_death, seed)

#' @rdname rust-internals
#' @export
project_dex__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, baseline_employed, seed
) .Call(wrap__project_dex__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, baseline_employed, seed)

#' @rdname rust-internals
#' @export
project_air__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    year_of_death, month_of_death, day_of_death, seed, reference_year
) .Call(wrap__project_air__,
    aeuid, birth_year, sex, state, indigenous,
    year_of_death, month_of_death, day_of_death, seed, reference_year)

#' @rdname rust-internals
#' @export
project_amep__ <- function(
    aeuid, birth_year, country_of_birth, year_of_arrival, year_of_death, seed
) .Call(wrap__project_amep__,
    aeuid, birth_year, country_of_birth, year_of_arrival, year_of_death, seed)

#' @rdname rust-internals
#' @export
project_nacdc__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, seed, reference_year
) .Call(wrap__project_nacdc__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, seed, reference_year)

#' @rdname rust-internals
#' @export
project_births__ <- function(
    aeuid, spine_id, birth_year, sex, state, indigenous,
    country_of_birth, seed
) .Call(wrap__project_births__,
    aeuid, spine_id, birth_year, sex, state, indigenous,
    country_of_birth, seed)

#' @rdname rust-internals
#' @export
project_aedc__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, seed, cycle_year
) .Call(wrap__project_aedc__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, seed, cycle_year)

#' @rdname rust-internals
#' @export
project_acld__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, baseline_employed,
    baseline_income, seed
) .Call(wrap__project_acld__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, baseline_employed,
    baseline_income, seed)

#' @rdname rust-internals
#' @export
project_sdac__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, baseline_employed,
    disability_severity, disability_onset_year, person_type, seed, survey_year
) .Call(wrap__project_sdac__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, education, baseline_employed,
    disability_severity, disability_onset_year, person_type, seed, survey_year)

#' @rdname rust-internals
#' @export
build_itr_tables__ <- function(
    filers_aeuid, filers_fy, filers_total_gross, filers_total_tax,
    spine_aeuid, spine_anzsco, spine_industry, spine_archetype,
    spine_birth_yr, occ_panel_aeuid, occ_panel_year, occ_panel_anzsco,
    seed
) .Call(wrap__build_itr_tables__,
    filers_aeuid, filers_fy, filers_total_gross, filers_total_tax,
    spine_aeuid, spine_anzsco, spine_industry, spine_archetype,
    spine_birth_yr, occ_panel_aeuid, occ_panel_year, occ_panel_anzsco,
    seed)

#' @rdname rust-internals
#' @export
build_ps_table__ <- function(
    aeuid_ato, year, employer_id, gross_annual, anzsco_major, seed
) .Call(wrap__build_ps_table__,
    aeuid_ato, year, employer_id, gross_annual, anzsco_major, seed)

#' @rdname rust-internals
#' @export
build_spine_template_parquet__ <- function(
    n_template, seed, out_path
) .Call(wrap__build_spine_template_parquet__,
    n_template, seed, out_path)

#' @rdname rust-internals
#' @export
generate_spine_from_template_parquet__ <- function(
    template_path, n, seed, out_path, agency_codes
) .Call(wrap__generate_spine_from_template_parquet__,
    template_path, n, seed, out_path, agency_codes)

#' @rdname rust-internals
#' @export
generate_mbs_full__ <- function(
    aeuid_dhda, birth_year, month_of_birth, sex, state,
    year_of_death, month_of_death, day_of_death,
    baseline_income, baseline_employed, disability_onset_year,
    disability_severity, disability_is_dc,
    item_num, item_category, item_group, item_sub_heading, item_benefit_type,
    item_schedule_fee, item_benefit_75, item_benefit_85, item_benefit_100,
    item_weight, out_dir, year_start, year_end, seed, chunk_persons
) .Call(wrap__generate_mbs_full__,
    aeuid_dhda, birth_year, month_of_birth, sex, state,
    year_of_death, month_of_death, day_of_death,
    baseline_income, baseline_employed, disability_onset_year,
    disability_severity, disability_is_dc,
    item_num, item_category, item_group, item_sub_heading, item_benefit_type,
    item_schedule_fee, item_benefit_75, item_benefit_85, item_benefit_100,
    item_weight, out_dir, year_start, year_end, seed, chunk_persons)

#' @rdname rust-internals
#' @export
generate_pbs_full__ <- function(
    aeuid_dhda, birth_year, month_of_birth, sex, state,
    year_of_death, month_of_death, day_of_death,
    baseline_income, baseline_employed, disability_onset_year,
    disability_severity, disability_is_dc,
    pbs_code, atc_level1, benefit_type,
    claimed_price, pack_size, number_of_repeats, item_weight,
    out_dir, year_start, year_end, seed, chunk_persons
) .Call(wrap__generate_pbs_full__,
    aeuid_dhda, birth_year, month_of_birth, sex, state,
    year_of_death, month_of_death, day_of_death,
    baseline_income, baseline_employed, disability_onset_year,
    disability_severity, disability_is_dc,
    pbs_code, atc_level1, benefit_type,
    claimed_price, pack_size, number_of_repeats, item_weight,
    out_dir, year_start, year_end, seed, chunk_persons)

#' @rdname rust-internals
#' @export
generate_pit_ps_full_to_parquet__ <- function(
    id, aeuid_ato, birth_year, baseline_employed, baseline_income,
    baseline_hours, anzsco_major, industry, anzsco_code, task_physical,
    archetype, disability_onset_year, disability_is_dc, disability_severity,
    disability_dose, years, seed, out_dir, occ_out_dir, product_names
) .Call(wrap__generate_pit_ps_full_to_parquet__,
    id, aeuid_ato, birth_year, baseline_employed, baseline_income,
    baseline_hours, anzsco_major, industry, anzsco_code, task_physical,
    archetype, disability_onset_year, disability_is_dc, disability_severity,
    disability_dose, years, seed, out_dir, occ_out_dir, product_names)

#' @rdname rust-internals
#' @export
generate_pit_itr_full_to_parquet__ <- function(
    spine_aeuid, spine_anzsco, spine_industry, spine_archetype,
    spine_birth_yr, ps_file_paths, ps_years, occ_panel_paths, years,
    product_name_by_yr_type, out_dir, seed
) .Call(wrap__generate_pit_itr_full_to_parquet__,
    spine_aeuid, spine_anzsco, spine_industry, spine_archetype,
    spine_birth_yr, ps_file_paths, ps_years, occ_panel_paths, years,
    product_name_by_yr_type, out_dir, seed)

#' @rdname rust-internals
#' @export
write_stp_dil_pay_events_to_parquet__ <- function(
    spine_id, aeuid_ato, birth_year, state, baseline_income,
    sa2_asgs_2021, stp_meshblock_abs, seed, year, month, extended,
    panel_fy_gross, out_path
) .Call(wrap__write_stp_dil_pay_events_to_parquet__,
    spine_id, aeuid_ato, birth_year, state, baseline_income,
    sa2_asgs_2021, stp_meshblock_abs, seed, year, month, extended,
    panel_fy_gross, out_path)

#' @rdname rust-internals
#' @export
write_stp_dil_jobs_to_parquet__ <- function(
    spine_id, aeuid_ato, seed, fy_end, out_path
) .Call(wrap__write_stp_dil_jobs_to_parquet__,
    spine_id, aeuid_ato, seed, fy_end, out_path)

#' @rdname rust-internals
#' @export
write_stp_dil_etp_to_parquet__ <- function(
    spine_id, aeuid_ato, baseline_income, seed, fy_end, out_path
) .Call(wrap__write_stp_dil_etp_to_parquet__,
    spine_id, aeuid_ato, baseline_income, seed, fy_end, out_path)

#' @rdname rust-internals
#' @export
project_busown_to_parquet__ <- function(
    aeuid, birth_year, baseline_employed, seed, fy_start, fy_end,
    out_dir, product_prefix
) .Call(wrap__project_busown_to_parquet__,
    aeuid, birth_year, baseline_employed, seed, fy_start, fy_end,
    out_dir, product_prefix)

#' @rdname rust-internals
#' @export
project_pit_ie_to_parquet__ <- function(
    id, aeuid, birth_year, baseline_employed, baseline_income, baseline_hours,
    anzsco_major, anzsco_code, industry, archetype, disability_onset_year,
    disability_is_dc, disability_severity, disability_dose, task_physical,
    education, seed, fy_start, fy_end, out_dir, product_fmt
) .Call(wrap__project_pit_ie_to_parquet__,
    id, aeuid, birth_year, baseline_employed, baseline_income, baseline_hours,
    anzsco_major, anzsco_code, industry, archetype, disability_onset_year,
    disability_is_dc, disability_severity, disability_dose, task_physical,
    education, seed, fy_start, fy_end, out_dir, product_fmt)

#' @rdname rust-internals
#' @export
project_sae_to_parquet__ <- function(
    aeuid, birth_year, sex, state, baseline_employed, baseline_income,
    seed, fy_start, fy_end, out_dir, product_prefix
) .Call(wrap__project_sae_to_parquet__,
    aeuid, birth_year, sex, state, baseline_employed, baseline_income,
    seed, fy_start, fy_end, out_dir, product_prefix)

#' @rdname rust-internals
#' @export
project_cgt_to_parquet__ <- function(
    aeuid, birth_year, baseline_income, seed, fy_start, fy_end,
    out_dir, product_prefix
) .Call(wrap__project_cgt_to_parquet__,
    aeuid, birth_year, baseline_income, seed, fy_start, fy_end,
    out_dir, product_prefix)

#' @rdname rust-internals
#' @export
project_rps_to_parquet__ <- function(
    aeuid, birth_year, baseline_income, state, seed, fy_start, fy_end,
    out_dir, product_prefix
) .Call(wrap__project_rps_to_parquet__,
    aeuid, birth_year, baseline_income, state, seed, fy_start, fy_end,
    out_dir, product_prefix)

#' @rdname rust-internals
#' @export
project_ndis_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    disability_onset_year, disability_severity, person_type,
    comorbidity_flags, country_of_birth_sacc, sa2,
    seed, out_participants, out_plansupports, out_payments
) .Call(wrap__project_ndis_to_parquet__,
    aeuid, birth_year, sex, state, indigenous,
    disability_onset_year, disability_severity, person_type,
    comorbidity_flags, country_of_birth_sacc, sa2,
    seed, out_participants, out_plansupports, out_payments)

#' @rdname rust-internals
#' @export
project_apprentice_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, anzsco_code, industry,
    year_of_death, month_of_death, day_of_death, seed, out_path
) .Call(wrap__project_apprentice_to_parquet__,
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, anzsco_code, industry,
    year_of_death, month_of_death, day_of_death, seed, out_path)

#' @rdname rust-internals
#' @export
project_dex_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, baseline_employed, baseline_income, sa2, disability_severity,
    seed, out_client, out_attendance, out_assessment
) .Call(wrap__project_dex_to_parquet__,
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, baseline_employed, baseline_income, sa2, disability_severity,
    seed, out_client, out_attendance, out_assessment)

#' @rdname rust-internals
#' @export
project_air_to_parquet__ <- function(
    aeuid, spine_id, birth_year, sex, state, indigenous,
    year_of_death, month_of_death, day_of_death, seed,
    reference_year, out_path
) .Call(wrap__project_air_to_parquet__,
    aeuid, spine_id, birth_year, sex, state, indigenous,
    year_of_death, month_of_death, day_of_death, seed,
    reference_year, out_path)

#' @rdname rust-internals
#' @export
project_amep_to_parquet__ <- function(
    aeuid, birth_year, country_of_birth, year_of_arrival, year_of_death,
    seed, out_path
) .Call(wrap__project_amep_to_parquet__,
    aeuid, birth_year, country_of_birth, year_of_arrival, year_of_death,
    seed, out_path)

#' @rdname rust-internals
#' @export
project_nacdc_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    sa2, seed, reference_year, aged_recipient_out_path,
    aged_service_out_path, chsp_out_path, hcp_out_path,
    rac_out_path, tcp_out_path
) .Call(wrap__project_nacdc_to_parquet__,
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    sa2, seed, reference_year, aged_recipient_out_path,
    aged_service_out_path, chsp_out_path, hcp_out_path,
    rac_out_path, tcp_out_path)

#' @rdname rust-internals
#' @export
project_aedc_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    seed, cycle_year, out_path
) .Call(wrap__project_aedc_to_parquet__,
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    seed, cycle_year, out_path)

#' @rdname rust-internals
#' @export
project_acld_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, baseline_employed, baseline_income, seed, out_path
) .Call(wrap__project_acld_to_parquet__,
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, baseline_employed, baseline_income, seed, out_path)

#' @rdname rust-internals
#' @export
project_sdac_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, baseline_employed, disability_severity, disability_onset_year, person_type,
    seed, survey_year, out_path
) .Call(wrap__project_sdac_to_parquet__,
    aeuid, birth_year, sex, state, indigenous, country_of_birth,
    education, baseline_employed, disability_severity, disability_onset_year, person_type,
    seed, survey_year, out_path)

#' @rdname rust-internals
#' @export
project_combined_indigenous_to_parquet__ <- function(spine_id, indigenous, out_path) {
  .Call(wrap__project_combined_indigenous_to_parquet__, spine_id, indigenous, out_path)
}

#' @rdname rust-internals
#' @export
project_mcd_to_parquet__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, year_of_death, month_of_death, seed, out_path
) .Call(wrap__project_mcd_to_parquet__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, year_of_death, month_of_death, seed, out_path)

#' @rdname rust-internals
#' @export
project_mt_demogs_to_parquet__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, seed, out_path
) .Call(wrap__project_mt_demogs_to_parquet__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, seed, out_path)

#' @rdname rust-internals
#' @export
project_visa_to_parquet__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, indigenous, anzsco_code, baseline_income, seed, out_path
) .Call(wrap__project_visa_to_parquet__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, indigenous, anzsco_code, baseline_income, seed, out_path)

#' @rdname rust-internals
#' @export
project_sdb_to_parquet__ <- function(
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, education, anzsco_code, seed, out_path
) .Call(wrap__project_sdb_to_parquet__,
    aeuid, birth_year, sex, state, country_of_birth,
    year_of_arrival, education, anzsco_code, seed, out_path)

#' @rdname rust-internals
#' @export
project_births_to_parquet__ <- function(
    aeuid, spine_id, birth_year, sex, state, indigenous,
    country_of_birth, seed, out_path
) .Call(wrap__project_births_to_parquet__,
    aeuid, spine_id, birth_year, sex, state, indigenous,
    country_of_birth, seed, out_path)

#' @rdname rust-internals
#' @export
project_travellers_to_parquet__ <- function(
    aeuid, birth_year, month_of_birth, country_of_birth, year_of_arrival,
    year_of_death, month_of_death, day_of_death, residence_seed,
    seed, min_year, max_year, out_dir, combined_name, erp_name, pp_name
) .Call(wrap__project_travellers_to_parquet__,
    aeuid, birth_year, month_of_birth, country_of_birth, year_of_arrival,
    year_of_death, month_of_death, day_of_death, residence_seed,
    seed, min_year, max_year, out_dir, combined_name, erp_name, pp_name)

#' @rdname rust-internals
#' @export
project_deaths_to_parquet__ <- function(
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, year_of_death, month_of_death, day_of_death,
    seed, min_year, max_year, out_dir
) .Call(wrap__project_deaths_to_parquet__,
    aeuid, birth_year, sex, state, indigenous,
    country_of_birth, year_of_death, month_of_death, day_of_death,
    seed, min_year, max_year, out_dir)
